import type {
	CompanionMigrationAction,
	CompanionMigrationFeedback,
	CompanionOptionValues,
	CompanionUpgradeContext,
	CompanionStaticUpgradeProps,
	CompanionStaticUpgradeResult,
	CompanionStaticUpgradeScript,
} from '@companion-module/base'
import { normalizeInteractivity, type ModuleConfig } from './config.js'
import { ChannelType } from './protocol/constants.js'

const BLOCKED_LEGACY_ACTION = 'legacy_unsafe_action'

// These action IDs existed in 0.2.0 but were removed or replaced. Companion
// keeps action references by ID, so leaving them untouched would create silent
// orphaned buttons after an upgrade. Keep the button visible as a blocked
// action with an actionable explanation instead.
const REMOVED_ACTION_REASONS: Readonly<Record<string, string>> = {
	change_preset: 'Preset change was removed; review and recreate this action with a supported workflow.',
	store_preset: 'Preset store was removed; review and recreate this action with a supported workflow.',
	set_polarity: 'Polarity control was removed; review and recreate this action with a supported workflow.',
	set_matrix: 'Matrix assignment was removed; review and recreate this action with a supported workflow.',
	snapshot_apply: 'Snapshot Apply was replaced by Snapshot Apply (by name); select the snapshot again.',
	snapshot_store: 'Snapshot Store was removed; review and recreate this action with a supported workflow.',
	snapshot_delete: 'Snapshot Delete was removed; review and recreate this action with a supported workflow.',
	rearm_all_input_priority: 'Rearm All Inputs was removed; review and recreate this action with a supported workflow.',
	rearm_all_aux_priority: 'Aux priority rearm was removed because H2L is documented only for Input DSP.',
}

/** Translate the pre-0.3 channel ids to the documented Newton channel ids. */
function migrateChannelType(value: unknown): number | null {
	const oldValue = Number(value)
	switch (oldValue) {
		case 0:
		case 1:
			return oldValue
		case 4:
			return ChannelType.OutputGroup
		case 5:
			return ChannelType.Trimmer
		case 6:
			return ChannelType.AuxMixer
		case 7:
			return ChannelType.MatrixMixer
		// Old 2/3 meant Input/Output Patch. They have no equivalent in the
		// documented ChannelType list and must never silently become Aux/Matrix.
		case 2:
		case 3:
		default:
			return null
	}
}

function block(action: CompanionMigrationAction, reason: string): CompanionMigrationAction {
	return {
		...action,
		actionId: BLOCKED_LEGACY_ACTION,
		options: { reason },
	}
}

function upgradeActions(actions: CompanionMigrationAction[]): CompanionMigrationAction[] {
	return actions.map((action) => {
		const removalReason = REMOVED_ACTION_REASONS[action.actionId]
		if (removalReason) return block(action, removalReason)
		if (action.actionId === 'set_mute') {
			return block(action, 'Per-channel mute was removed because it could overwrite the channel gain.')
		}
		if (action.actionId === 'set_delay') {
			return block(action, 'Delay units changed from milliseconds to samples; review and recreate this action.')
		}
		if (action.actionId === 'set_pan') {
			return block(action, 'Pan is now Aux Mixer only and uses 0..1 (center 0.5); review and recreate this action.')
		}

		const options = { ...action.options }
		if ('channelType' in options) {
			const migrated = migrateChannelType(options.channelType)
			if (migrated === null) {
				return block(action, 'The saved channel type is no longer supported by the Newton protocol.')
			}
			options.channelType = migrated
		}

		if (action.actionId === 'read_priority_list' || action.actionId === 'rearm_priority') {
			if (Number(action.options.channelType) !== Number(ChannelType.InputDsp)) {
				return block(action, 'Priority H2L read/rearm is documented only for Input DSP channels.')
			}
			delete options.channelType
			if (action.actionId === 'rearm_priority') options.rearmIndex = 0
		}
		return { ...action, options }
	})
}

function upgradeFeedbacks(feedbacks: CompanionMigrationFeedback[]): CompanionMigrationFeedback[] {
	return feedbacks.map((feedback) => {
		if (!('channelType' in feedback.options)) return feedback
		const migrated = migrateChannelType(feedback.options.channelType)
		// Preserve the feedback entry but make it inert. Mapping legacy Input/Output
		// Patch ids 2/3 to today's Aux/Matrix values would report a false state.
		if (migrated === null) return { ...feedback, options: { ...feedback.options, channelType: -1 } }
		const options: CompanionOptionValues = { ...feedback.options, channelType: migrated }
		// These values were generated by the old Input Priority status presets.
		// Their healthy H2L source is AES3 8+i, not i.
		if (
			feedback.feedbackId === 'priority_overridden' &&
			migrated === Number(ChannelType.InputDsp) &&
			Number.isInteger(Number(options.patchIndex)) &&
			Number(options.patchIndex) >= 0 &&
			Number(options.patchIndex) <= 15 &&
			Number(options.highestSource) === Number(options.patchIndex)
		) {
			options.highestSource = Number(options.patchIndex) + 8
		}
		return { ...feedback, options }
	})
}

export const UpgradeScripts: CompanionStaticUpgradeScript<ModuleConfig>[] = [
	(
		_context: CompanionUpgradeContext<ModuleConfig>,
		props: CompanionStaticUpgradeProps<ModuleConfig>,
	): CompanionStaticUpgradeResult<ModuleConfig> => {
		return {
			// Legacy monitor-type fixups were dropped: the next script strips every
			// stored tuning field anyway, so only actions/feedbacks need migration.
			updatedConfig: null,
			updatedActions: upgradeActions(props.actions),
			updatedFeedbacks: upgradeFeedbacks(props.feedbacks),
		}
	},
	(
		_context: CompanionUpgradeContext<ModuleConfig>,
		props: CompanionStaticUpgradeProps<ModuleConfig>,
	): CompanionStaticUpgradeResult<ModuleConfig> => {
		// The config UI now exposes only the device IP. Drop every stored legacy
		// tuning field so old (possibly invalid) values never shadow the fixed
		// defaults in SETTINGS.
		return {
			updatedConfig: props.config
				? { host: props.config.host ?? '', interactivity: normalizeInteractivity(props.config.interactivity) }
				: null,
			updatedActions: [],
			updatedFeedbacks: [],
		}
	},
	(
		_context: CompanionUpgradeContext<ModuleConfig>,
		props: CompanionStaticUpgradeProps<ModuleConfig>,
	): CompanionStaticUpgradeResult<ModuleConfig> => {
		// Operator-facing input/patch numbering moved from protocol 0-based to
		// 1-based. Shift stored options so existing buttons keep their target.
		const updatedActions: CompanionMigrationAction[] = []
		for (const action of props.actions) {
			if (action.actionId !== 'rearm_priority' && action.actionId !== 'read_priority_list') continue
			const channelIndex = Number(action.options.channelIndex)
			updatedActions.push({
				...action,
				options: {
					...action.options,
					channelIndex: (Number.isInteger(channelIndex) && channelIndex >= 0 ? channelIndex : 0) + 1,
				},
			})
		}
		const updatedFeedbacks: CompanionMigrationFeedback[] = []
		for (const feedback of props.feedbacks) {
			if (feedback.feedbackId !== 'priority_active_source' && feedback.feedbackId !== 'priority_overridden') continue
			const patchIndex = Number(feedback.options.patchIndex)
			updatedFeedbacks.push({
				...feedback,
				options: {
					...feedback.options,
					patchIndex: (Number.isInteger(patchIndex) && patchIndex >= 0 ? patchIndex : 0) + 1,
				},
			})
		}
		return { updatedConfig: null, updatedActions, updatedFeedbacks }
	},
	(
		_context: CompanionUpgradeContext<ModuleConfig>,
		props: CompanionStaticUpgradeProps<ModuleConfig>,
	): CompanionStaticUpgradeResult<ModuleConfig> => {
		// The priority feedbacks now compare the live 0x2B active source against
		// the 0x91 channel list, so the manually entered expected source and the
		// channel type are gone. Aux Mixer variants cannot be evaluated anymore
		// (0x91 is Input DSP only) and are made inert instead of silently
		// pointing at the wrong input.
		const updatedFeedbacks: CompanionMigrationFeedback[] = []
		for (const feedback of props.feedbacks) {
			if (feedback.feedbackId !== 'priority_active_source' && feedback.feedbackId !== 'priority_overridden') continue
			const wasAux =
				'channelType' in feedback.options && Number(feedback.options.channelType) !== Number(ChannelType.InputDsp)
			const patchIndex = Number(feedback.options.patchIndex)
			updatedFeedbacks.push({
				...feedback,
				options: { patchIndex: wasAux || !Number.isInteger(patchIndex) ? 0 : patchIndex },
			})
		}
		return { updatedConfig: null, updatedActions: [], updatedFeedbacks }
	},
	(
		_context: CompanionUpgradeContext<ModuleConfig>,
		props: CompanionStaticUpgradeProps<ModuleConfig>,
	): CompanionStaticUpgradeResult<ModuleConfig> => {
		// The styled boolean priority feedbacks were replaced by the single
		// 'input_patch_monitor' advanced feedback (no layered style overrides).
		// Convert stored ones so old buttons keep monitoring their input; the
		// fixed-monitor variants fall back to the monitored input 1.
		const updatedFeedbacks: CompanionMigrationFeedback[] = []
		for (const feedback of props.feedbacks) {
			if (feedback.feedbackId === 'priority_active_source' || feedback.feedbackId === 'priority_overridden') {
				const patchIndex = Number(feedback.options.patchIndex)
				updatedFeedbacks.push({
					...feedback,
					feedbackId: 'input_patch_monitor',
					options: {
						patchIndex: Number.isInteger(patchIndex) && patchIndex >= 1 && patchIndex <= 16 ? patchIndex : 0,
					},
				})
			} else if (feedback.feedbackId === 'priority_backup_active' || feedback.feedbackId === 'priority_manual_forced') {
				updatedFeedbacks.push({
					...feedback,
					feedbackId: 'input_patch_monitor',
					options: { patchIndex: 1 },
				})
			}
		}
		return { updatedConfig: null, updatedActions: [], updatedFeedbacks }
	},
	(
		_context: CompanionUpgradeContext<ModuleConfig>,
		props: CompanionStaticUpgradeProps<ModuleConfig>,
	): CompanionStaticUpgradeResult<ModuleConfig> => {
		// The rearm slot option was removed: rearming always restarts the backup
		// strategy from slot 0. Drop the stored option so old buttons keep working.
		const updatedActions: CompanionMigrationAction[] = []
		for (const action of props.actions) {
			if (action.actionId !== 'rearm_priority' || !('rearmIndex' in action.options)) continue
			const options = { ...action.options }
			delete options.rearmIndex
			updatedActions.push({ ...action, options })
		}
		return { updatedConfig: null, updatedActions, updatedFeedbacks: [] }
	},
	(
		_context: CompanionUpgradeContext<ModuleConfig>,
		props: CompanionStaticUpgradeProps<ModuleConfig>,
	): CompanionStaticUpgradeResult<ModuleConfig> => {
		// Set Gain was the last operator-facing action exposing Newton's raw
		// zero-based channel index. Preserve the physical target while moving the
		// saved UI value to the new one-based Channel field.
		const updatedActions: CompanionMigrationAction[] = []
		for (const action of props.actions) {
			if (action.actionId !== 'set_gain') continue
			const channelIndex = Number(action.options.channelIndex)
			updatedActions.push({
				...action,
				options: {
					...action.options,
					channelIndex:
						Number.isInteger(channelIndex) && channelIndex >= 0 && channelIndex <= 287 ? channelIndex + 1 : 1,
				},
			})
		}
		return { updatedConfig: null, updatedActions, updatedFeedbacks: [] }
	},
	(
		_context: CompanionUpgradeContext<ModuleConfig>,
		props: CompanionStaticUpgradeProps<ModuleConfig>,
	): CompanionStaticUpgradeResult<ModuleConfig> => {
		// The last-action feedbacks gained a scope option and now default to
		// watching only their own button. Feedbacks saved before the option
		// existed relied on the module-wide behaviour of 1.0.0: keep it for them.
		const updatedFeedbacks: CompanionMigrationFeedback[] = []
		for (const feedback of props.feedbacks) {
			if (feedback.feedbackId !== 'last_action_success' && feedback.feedbackId !== 'last_action_error') continue
			if ('scope' in feedback.options) continue
			updatedFeedbacks.push({ ...feedback, options: { ...feedback.options, scope: 'global' } })
		}
		return { updatedConfig: null, updatedActions: [], updatedFeedbacks }
	},
]
